import { describe, expect, it } from "vitest"

import { isApiKeyFormat } from "./api-key-format"

describe("API key format", () => {
  it("accepts a live key generated by the service", () => {
    expect(isApiKeyFormat(`llk_live_${"a".repeat(43)}`)).toBe(true)
  })

  it("rejects keys with the wrong prefix or length", () => {
    expect(isApiKeyFormat(`llk_test_${"a".repeat(43)}`)).toBe(false)
    expect(isApiKeyFormat(`llk_live_${"a".repeat(42)}`)).toBe(false)
    expect(isApiKeyFormat("llk_live_" + " ".repeat(43))).toBe(false)
  })
})
